kind: pipeline
type: docker
name: android

steps:
  - name: build
    image: benjyair/android-env
#    image: benjyair/android-env-gradle
    commands:
      - gradle assembleEngRelease

  - name: upload
    image: minio/mc
    environment:
      ACCESS_KEY:
        from_secret: minio_access_key
      SECRET_KEY:
        from_secret: minio_secret_key
    commands:
      - mc alias set minio http://192.168.192.1:9090 $ACCESS_KEY $SECRET_KEY
      - cd app/build/outputs/apk/eng/release
      - apk_file=`ls | head -1`
      - mc cp $apk_file minio/draque

  - name: notify-success
    image: curlimages/curl
    environment:
      CHANIFY_TOKEN:
        from_secret: chanify_token
    commands:
      - cd app/build/outputs/apk/eng/release
      - apk_file=`ls | head -1`
      - curl --form-string "text=Build and upload Success. MinIO[$apk_file]" "http://192.168.1.100:9070/v1/sender/$CHANIFY_TOKEN"

  - name: notify-failure
    image: curlimages/curl
    environment:
      CHANIFY_TOKEN:
        from_secret: chanify_token
    commands:
      - curl --form-string "text=Build and upload failure." "http://192.168.1.100:9070/v1/sender/$CHANIFY_TOKEN"
    when:
      status:
        - failure
